# Release-hygiene gate for the precompiled signer NIF.
#
# `checksum-Elixir.Hyperliquid.Signer.exs` is regenerated by hand
# (`mix rustler_precompiled.download --all`) after the tag build and before
# `mix hex.publish`. Nothing used to notice when that step was skipped: the
# moment `@version` in mix.exs moves ahead of the checksum file, every
# consumer's checksum lookup misses and `RustlerPrecompiled` fails at compile
# time — or, worse, `fail-fast: false` lets 17 of 18 matrix jobs succeed and
# ships a release that only looks complete.
#
# This script asserts:
#   1. every entry in the checksum file is for the current mix.exs @version;
#   2. there is exactly one entry per (nif version x target) in the
#      .github/workflows/nif_build.yml matrix — no gaps, no strays;
#   3. every checksum is a well-formed sha256.
#
# Run: elixir scripts/verify_nif_checksums.exs

defmodule VerifyNifChecksums do
  @checksum_file "checksum-Elixir.Hyperliquid.Signer.exs"
  @mix_file "mix.exs"
  @workflow ".github/workflows/nif_build.yml"

  def run do
    version = version!()
    {nif_versions, targets} = matrix!()
    entries = entries!()

    expected =
      for nif <- nif_versions, target <- targets do
        {nif, target}
      end

    errors =
      []
      |> check_versions(entries, version)
      |> check_sha256(entries)
      |> check_coverage(entries, expected, version)

    if errors == [] do
      IO.puts("""
      OK: #{map_size(entries)} checksum entries for v#{version}
          (#{length(nif_versions)} NIF versions x #{length(targets)} targets).
      """)
    else
      IO.puts(:stderr, "#{@checksum_file} is not release-ready:\n")
      Enum.each(errors, &IO.puts(:stderr, "  - #{&1}"))

      IO.puts(:stderr, """

      Regenerate it after the tag build completes:

          MIX_ENV=dev mix rustler_precompiled.download Hyperliquid.Signer --all --print
      """)

      System.halt(1)
    end
  end

  defp version! do
    case Regex.run(~r/@version\s+"([^"]+)"/, File.read!(@mix_file)) do
      [_, version] -> version
      _ -> raise "could not read @version from #{@mix_file}"
    end
  end

  # Minimal, purpose-built scrape of the build matrix — no YAML dep.
  defp matrix! do
    yaml = File.read!(@workflow)

    nif_versions =
      case Regex.run(~r/nif:\s*\[([^\]]+)\]/, yaml) do
        [_, list] ->
          list
          |> String.split(",")
          |> Enum.map(&(&1 |> String.trim() |> String.trim("\"")))

        _ ->
          raise "could not read the `nif:` matrix from #{@workflow}"
      end

    targets =
      ~r/target:\s*([a-z0-9_\-]+)/
      |> Regex.scan(yaml)
      |> Enum.map(fn [_, target] -> target end)
      |> Enum.uniq()

    if targets == [], do: raise("could not read `target:` entries from #{@workflow}")

    {nif_versions, targets}
  end

  defp entries! do
    {map, _} = Code.eval_file(@checksum_file)
    map
  end

  defp check_versions(errors, entries, version) do
    wrong =
      entries
      |> Map.keys()
      |> Enum.reject(&String.contains?(&1, "-v#{version}-"))

    case wrong do
      [] -> errors
      names -> errors ++ ["#{length(names)} entries are not for v#{version}: #{inspect(names)}"]
    end
  end

  defp check_sha256(errors, entries) do
    bad =
      for {name, sum} <- entries,
          not (is_binary(sum) and Regex.match?(~r/^sha256:[0-9a-f]{64}$/, sum)),
          do: name

    case bad do
      [] -> errors
      names -> errors ++ ["malformed sha256 for: #{inspect(names)}"]
    end
  end

  defp check_coverage(errors, entries, expected, version) do
    keys = Map.keys(entries)

    missing =
      for {nif, target} <- expected,
          not Enum.any?(keys, &covers?(&1, version, nif, target)),
          do: "nif-#{nif}/#{target}"

    extra =
      Enum.reject(keys, fn key ->
        Enum.any?(expected, fn {nif, target} -> covers?(key, version, nif, target) end)
      end)

    errors
    |> then(fn e ->
      if missing == [], do: e, else: e ++ ["missing artifacts: #{inspect(missing)}"]
    end)
    |> then(fn e ->
      if extra == [], do: e, else: e ++ ["unexpected artifacts: #{inspect(extra)}"]
    end)
  end

  # Handles both `libsigner_nif-...so.tar.gz` (unix) and
  # `signer_nif-...dll.tar.gz` (windows) naming.
  defp covers?(key, version, nif, target) do
    String.contains?(key, "-v#{version}-nif-#{nif}-#{target}.")
  end
end

VerifyNifChecksums.run()
